name: 'Jira description to prs body'
description: 'Add jira description to Pull request'
branding:
  icon: "check-circle"
  color: "purple"
inputs:
  token:
    description: "Github access token"
    required: true
  orgUrl: 
    description: "organization's jira url"
    required: true
  jiraToken:
    description: "Jira token"
    required: true
  jiraUsername:
    description: "Jira username"
    required: true
  sonarQubeUrl:
    description: "organization's sonarqube url"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'